// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx7yfnKcxi2vgZgeP2Ah1OO7z17Rz4km4',
    appId: '1:240464915606:web:01511bc12211be552da6b7',
    messagingSenderId: '240464915606',
    projectId: 'education-kiwiz',
    authDomain: 'education-kiwiz.firebaseapp.com',
    storageBucket: 'education-kiwiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8ii-zzqyYaRsnQHbnE5wSCVizbOiTsA',
    appId: '1:240464915606:android:4b8b6a99897b68012da6b7',
    messagingSenderId: '240464915606',
    projectId: 'education-kiwiz',
    storageBucket: 'education-kiwiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClen9JjdaxsOSUL399JchjE2KCa4Kp1ic',
    appId: '1:240464915606:ios:f71c468d31d1eae32da6b7',
    messagingSenderId: '240464915606',
    projectId: 'education-kiwiz',
    storageBucket: 'education-kiwiz.appspot.com',
    iosClientId: '240464915606-pf0anp26iu5vi1a2luhqcsoremrhcf5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationKiwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClen9JjdaxsOSUL399JchjE2KCa4Kp1ic',
    appId: '1:240464915606:ios:e4d6801ccb79627c2da6b7',
    messagingSenderId: '240464915606',
    projectId: 'education-kiwiz',
    storageBucket: 'education-kiwiz.appspot.com',
    iosClientId: '240464915606-3v291572gjpl1vrf3h9bssnbgkffr9qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.educationKiwiz.RunnerTests',
  );
}
